sudo: required
language: generic 
services:
  - docker

before_install: 
  - docker build -t gergis/client-test:latest -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true gergis/client-test npm test
after_success: 
  - docker build -t gergis/multi-container-client ./client
  - docker build -t gergis/multi-container-nginx ./nginx
  - docker build -t gergis/multi-container-server ./server
  - docker build -t gergis/multi-container-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gergis/multi-container-client
  - docker push gergis/multi-container-nginx
  - docker push gergis/multi-container-server
  - docker push gergis/multi-container-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-937630489434
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key : $AWS_SECRET_KEY